### ISSUE TITLE
`[lspconfig] Cannot access configuration for harper_ls.`

### ISSUE THREAD

**Issue by eamonburns** [Automattic/harper#76] opened 2024-04-16 18:22 UTC
I am trying to add `harper_ls` to Neovim, but I am getting this error whenever I start Neovim:

```
[lspconfig] Cannot access configuration for harper_ls. Ensure this server is listed in `server_configurations.md` or added as a custom server.
```

Here is the relevant section of my config (using `lazy.nvim`) (`-- ...` means omitted code):

```lua
-- lsp-zero.lua
return {
    "VonHeikemen/lsp-zero.nvim",
    -- ...
    config = function()
        -- ...
        local lsp_conf = require("lspconfig")
        -- ...
        lsp_conf.harper_ls.setup({
            settings = {
                ["harper-ls"] = {
                    linters = {
                        spell_check = true,
                        spelled_numbers = false,
                        an_a = true,
                        sentence_capitalization = true,
                        unclosed_quotes = true,
                        wrong_quotes = false,
                        long_sentences = true,
                        repeated_words = true,
                        spaces = true,
                        matcher = true
                    }
                }
            }
        })
        -- ...
    end
}

**Comment by Agent-E11** [comment] 2024-04-16 18:23
I installed it using `Mason.nvim`

**Comment by elijah-potter** [comment] 2024-04-17 15:45
I'd love to get this sorted out for you, but the issue isn't immediately obvious here. Would it be possible to get a copy of your full Neovim configuration so I can try it out on my machine?

**Comment by Agent-E11** [comment] 2024-04-17 16:56
I just created a repo containing all my Neovim config (I think) https://github.com/Agent-E11/nvim-config-copy

**Comment by Agent-E11** [comment] 2024-04-17 16:57
The config is dependent on _some_ environment variables, but it should have some defaults

**Comment by elijah-potter** [comment] 2024-04-17 17:22
Thanks for sending that over. It seems that we may need to add `harper-ls` to `mason-lspconfig.nvim`. I tried your configuration with @grantlemons [fork](https://github.com/grantlemons/mason-lspconfig.nvim) and it worked. I'll look into opening a pull request in the official repo.

For now, a short-term fix is to swap the version of `mason-lspconfig.nvim` you are using.

**Comment by Agent-E11** [comment] 2024-04-17 17:35
Thanks! So, should I change the repo of `mason.nvim` to grantlemons' fork?

Also, should this be a new issue on `mason.nvim`?

**Comment by grantlemons** [comment] 2024-04-17 17:53
This is a mason-lspconfig thing, and just adding support there should get it working for everyone.

I made that fork, which seems to fix everything, but wanted to make sure I was doing everything in line with whatever contribution policy/process before making the PR, that's the only reason it isn't in the official repo.

**Comment by grantlemons** [comment] 2024-04-17 20:41
@elijah-potter in the meantime it might be helpful to add this to the harper-ls readme.

**Comment by elijah-potter** [comment] 2024-05-13 16:54
I sat down today to fix this issue upstream--only to find out [someone already did it.](https://github.com/williamboman/mason-lspconfig.nvim/pull/406)

Huge thanks to @Su3h7aM!

I am going to close the issue as it appears the issue is resolved. Feel free to open it again if it persists.

**Closed by elijah-potter** 2024-05-13 16:54 UTC
Labels: harper-ls, config-options-prefs-settings
